### ISSUE TITLE
Question : How can i compile start.c visual studio

### ISSUE THREAD

**Issue by JHOHYEN** [py2exe/py2exe#106]
Hi there,
I'm trying to compile start.c because I'm curious about the process of how this code creates an exe.
but However, many errors occurred, among which "Identifier "PYTHONDLL" is not defined." of the problem occurred.
How can I handle this error and compile the existing c code in the source?

I am using Visual Studio 2019 of window10 and python version 3.8.

**Comment by albertosottile** [comment]
You can give a look at how Python is used to build the extension in the GitHub Actions workflow configuration, starting from here: https://github.com/py2exe/py2exe/blob/1071a13835d9aa9874d5868a2763366479869307/.github/workflows/CI.yml#L91
