### ISSUE TITLE
Build fails for py2exe-0.10.0.2

### ISSUE THREAD

**Issue by bozhinov** [py2exe/py2exe#110]
Hello,

I m trying to do pip upgrade from 0.9.2.2 to 0.10.0.2 on a Windows 10 x64 box with Python 3.10 x64
(there is no wheel for it yet)

I have Visual Studio Build Tools 2019 - 16.11.5 installed

I get a failure to build wheel:
` source/start.c(284): error C2017: illegal escape sequence
  source/start.c(284): error C2001: newline in constant
  source/start.c(285): error C2143: syntax error: missing ')' before 'if'
  source/start.c(289): error C2065: 'hgbl': undeclared identifier
  source/start.c(289): warning C4047: '=': 'int' differs in levels of indirection from 'HGLOBAL'
  source/start.c(291): error C2065: 'hgbl': undeclared identifier
  source/start.c(291): warning C4022: 'LockResource': pointer mismatch for actual parameter 1
  source/start.c(292): error C2017: illegal escape sequence
  source/start.c(292): error C2001: newline in constant
  source/start.c(293): error C2143: syntax error: missing ')' before '}'
  source/start.c(292): error C2198: 'MyLoadLibrary': too few arguments for call
  source/start.c(299): error C2017: illegal escape sequence
  source/start.c(299): error C2001: newline in constant
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2`

**Comment by bozhinov** [comment]
0.10.4.1 built and installed just fine

**Comment by bozhinov** [comment]
Totally get it. thank you. PIP is still unaware of the newer version which threw me off

Here is the warning I get using the example from the main page

C:\Python310\pkg.py2exe.py:1: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.core import setup

**Comment by albertosottile** [comment]
> Totally get it. thank you. PIP is still unaware of the newer version which threw me off

I can see the right version on PyPi `https://pypi.org/project/py2exe/`. However, you are using Python 3.10 which is not yet officially supported by py2exe. I plan to release 0.10.5.0 with 3.10 support as soon as I can get all the functional tests passed (I still miss wheels for numpy, matplotlib, wx_python, ...)

> C:\Python310\pkg.py2exe.py:1: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
from distutils.core import setup

Thanks for reporting the warning, I am well aware. Luckily, I still have a couple of years to deal with this.
