### ISSUE TITLE
Missing "run-py3.10-win32.exe" in Py2Exe installation for Python 3.10

### ISSUE THREAD

**Issue by Bursade** [py2exe/py2exe#116]
I'm following the tutorial of Py2Exe (http://www.py2exe.org/index.cgi/Tutorial) and got stuck on step 3 "Run your setup script".
It seems that one file called "run-py3.10-win32.exe" is missing from the installation because I get the following error:

`error: [Errno 2] No such file or directory: 'C:\\Users\\lauta\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\py2exe\\run-py3.10-win32.exe'`

I have Windows 11 Pro (21H2) and I've installed Python 3.10 from the Microsoft Store. To install "py2exe" module I run:
`pip3 install py2exe`

It seems that a file called "run-py3.10-win-amd64.exe" was created inside "...Python310\site-packages\py2exe\" but there's no file called "run-py3.10-win32.exe" (which is the one that I need, according to the error message).

EDIT: the version of Py2Exe that was installed using Pip is: 0.11.0.1

**Comment by albertosottile** [comment]
Hi, thanks for reporting this.

Please do not use the version of Python from the Microsoft Store, as it has caused several issues in the past. Instead, please download and install Python from the official website: [www.python.org](https://www.python.org/downloads/release/python-3100/). 

Let me know if you still see this error after uninstalling the Microsoft Store Python and installing the official Python distribution.

**Comment by albertosottile** [comment]
Closing this as no further information was provided.
