### ISSUE TITLE
error: [WinError 87] The parameter is incorrect.

### ISSUE THREAD

**Issue by adelpeyroux** [py2exe/py2exe#117]
# Problem

Our team encounter an issue using py2exe on our build server (Windows 10).

When we try to build an exe we get the following error : 

```
C:\workspace>python setup.py py2exe 
...
Building 'dist\app.exe'.
Add resource PYTHONSCRIPT/1(7744 bytes) to dist\app.exe
error: [WinError 87] The parameter is incorrect.
```

Please see our setup.py file :

```python
from distutils.core import setup
# noinspection PyUnresolvedReferences
import py2exe


setup(windows=['app.py'],
      options={
          "py2exe": {
              "excludes": ["tkinter"],
              "verbose": 4
          }
      })
```
# Possible Cause

We checked existing errors and we are already using a different python than the one from the windows store. Also the problems appeared today (in the past the build process ran perfectly fine), it seems that it came with a Windows update.

```
C:\workspace> python -m platform
Windows-10-10.0.19042-SP0
```

When we succeed to reproduce this bug on a working station we saw that Windows Defender was blocking and deleting `dist\app.exe` when py2exe started to create it. After disabling Windows Defender we succeed to build our exe. 

# Workaround 

Adding exclusion rules on our servers let us build our exe.

**Comment by albertosottile** [comment]
Thanks for reporting this. Unfortunately, I am unable to reproduce. 

I would ask you to report also the output of `ver`, as `platform` can be unreliable for Windows minors:
```
C:\Users\Alberto>python -m platform
Windows-10-10.0.19041-SP0

C:\Users\Alberto>ver

Microsoft Windows [Version 10.0.19043.1348]
```

On this system and Python 3.7 I can freeze apps with latest py2exe without experiencing the error you report.

**Comment by adelpeyroux** [comment]
Please find the requested informations here : 

```
C:\workspace>ver

Microsoft Windows [version 10.0.19042.1348]

C:\workspace>python -m platform
Windows-10-10.0.19042-SP0
```

Also we get the error using python 3.9.1 and 3.9.5.

**Comment by albertosottile** [comment]
I updated my PC to Python 3.9.5, so now I have matching `ver` and `platform` outputs, but I am still unable to reproduce. At this point, I do not know how I can help you…

**Comment by adelpeyroux** [comment]
Sorry for the late response :(

I think we can close the issue if you can't reproduce it. I think the problem came from a Windows Update and not from py2exe.
Thank you for your time !
