### ISSUE TITLE
Is there a way to package only the module that my program uses?

### ISSUE THREAD

**Issue by Tylersuard** [py2exe/py2exe#122]
I noticed that py2exe throws a lot of unnecessary packages into the dist folder, like tkinter, etc.  My script is super simple.  Is there any way to trim the fat?

**Comment by albertosottile** [comment]
If you are absolutely sure your project does not require some dependencies, you can use the `'excludes'` keyword to pass a list of modules that you do not want to include in the bundle.

Example:
```python
setup(console=[{ "script": "script.py"}],
      options={"py2exe": {
            "excludes": ['tcl', 'tkinter']}})
```

If you do this, I would encourage you to verify if the packaged bundle can still run without the explicitly excluded dependency.

**Comment by Tylersuard** [comment]
Thank you!  I really appreciate it.
