### ISSUE TITLE
Dependancies and building

### ISSUE THREAD

**Issue by HeavyTony2** [py2exe/py2exe#124]
Hello,
I decided to add py2exe's recipe to conda-forge. https://github.com/conda-forge/staged-recipes/pull/17596

Building wasn't easy.
First, "cachetools" and "pefile" are not properly listed in setup_requires. They're required for setup too.

Also, building requires a setuptools version below 60 except for Python 3.9.  When we tried to build it for 3.6, 3.7 and 3.8, there had that parsing issue with C code. https://github.com/py2exe/py2exe/issues/110

**Comment by albertosottile** [comment]
Thanks for reporting this. 
 
> First, "cachetools" and "pefile" are not properly listed in setup_requires. They're required for setup too.

I will add the `setup_requires` keyword in the next release.

> Also, building requires a setuptools version below 60 except for Python 3.9. When we tried to build it for 3.6, 3.7 and 3.8, there had that parsing issue with C code

In version 60, `setuptools` essentially integrated in its codebase the patch that was already present in the `setup.py` script of py2exe, making it redundant. I fixed this already in the `develop` branch (https://github.com/py2exe/py2exe/commit/4f8b5d60f127459837cf6f083eb857e264583479) but this has not yet been released. Also this fix will be included in the next release.

**Comment by albertosottile** [comment]
Fixed in 0.11.1.0. Thanks again for having reported this.
