### ISSUE TITLE
optimize is not being applied to library.zip

### ISSUE THREAD

**Issue by nchidsey** [py2exe/py2exe#125]
The optimize setting is not being applied to modules in the library.zip, even though it applies to the resource script string in the exe.  I am under the impression this ought to apply to the library.zip modules as well, as it did in the old python 2 version.

Reproduction:

setup.py:
```python
from setuptools import setup
import py2exe
setup(
    name='foo',
    console=['main.py'],
    options={
        'py2exe': {
            'optimize': 2,
        },
    },
)
```

main.py:
```python
'''Here is my docstring'''
assert False
print("hello world")
```

The zip file created has all `.pyc` extensions, and docstrings can be seen in the files regardless of the optimize setting.  But by commenting out the optimize line, the docstring and assertion do toggle in the main script resource of the exe.

Tested with
* python 3.7 + py2exe 0.10.0.4 and 0.11.0.1,
* python 3.9 + py2exe 0.11.0.1

**Comment by albertosottile** [comment]
Fixed in 0.11.1.0. Thanks again for having reported this.
