### ISSUE TITLE
missing Modules Python 3.10.1

### ISSUE THREAD

**Issue by hungth84** [py2exe/py2exe#128]
Hello! I converted to exe format with the following error. Can anyone help me explain why?
My setup.py :

`from distutils.core import setup
import py2exe

setup(console=['sendMoney3.py'])`

![image](https://user-images.githubusercontent.com/16811019/159709845-e752394f-3fdf-41ed-a594-80b9684f967e.png)

**Comment by RachelDong** [comment]
Hi, I'm facing the same problem with you. Have you solved this problem?

**Comment by Athanasius** [comment]
I believe the *list* of 'missing Modules' is just py2exe stating what it's found aren't explicitly included in the setup.py configuration, but it's going to add the necessary itself.

Certainly I get a whole lot of them listed for my builds, but the resulting program works perfectly.
