### ISSUE TITLE
Doesn't work Py2exeAndWin32com

### ISSUE THREAD

**Issue by jounts** [py2exe/py2exe#129]
Doesn't [Py2exeAndWin32com](http://www.py2exe.org/index.cgi/Py2exeAndWin32com) work anymore?

**Comment by albertosottile** [comment]
Hi, support for win32com objects was removed in version 0.10.x.

**Comment by OmniaGit** [comment]
There is any plan to support again win32com  ?
There are any other way to achieve the some result  with other software ?
we strongly need this feature !!

**Comment by albertosottile** [comment]
@OmniaGit No, there is no plan to support this feature. You are free to prepare and submit a PR that restores the functionality, or to fork the project as per your needs. I am not aware of any alternatives, but I am not a user of `win32com` so I would not know.
