### ISSUE TITLE
Doesn't include non-python files needed for library.zip

### ISSUE THREAD

**Issue by LukeDev42** [py2exe/py2exe#130]
I'm using a package call Dash, created by plotly. It uses json and js files to implement many features of the package. There isn't a way to force py2exe to recognize these non-python files as a needed for the package its collecting.
This is a picture of the dash package files in my virtual environment:
![image](https://user-images.githubusercontent.com/30641595/162283794-cafdb742-79ba-4e9b-b901-073aa3d5141c.png)
This is a picture of the same folder in library.zip of my py2exe output:
![image](https://user-images.githubusercontent.com/30641595/162288364-df2b24d7-1c08-453b-8e83-a7db94669849.png)
Looking at this doc page; http://py2exe.org/index.cgi/ListOfOptions, there doesn't seem to be an option to force it to include non-python files for a package.

**Comment by urishab** [comment]
Hi Luke 
I think you need to add those files as data files. 
This will add them to your library file.
See the example of MatPlotLib here:
https://www.py2exe.org/index.cgi/MatPlotLib

**Comment by albertosottile** [comment]
@LukeDev42 did you manage to add your data files as described by @urishab? If so, I would close this issue.

**Comment by albertosottile** [comment]
Closing this as no input was provided.
