### ISSUE TITLE
The windows_curses package can no longer be bundled

### ISSUE THREAD

**Issue by mharbison72** [py2exe/py2exe#132]
This used to work with the original py2 releases, but fails in the py3 releases with messages like `ImportError: No module named '_curses'` or `ImportError: Module '_curses' is in the "excludes" list`, depending on the version.  Bundling `curses` without `_curses.pyd` leads to an ImportError when attempting to use it.

I was able to bundle it successfully by dropping the `_curses` line from the exclude list here:

https://github.com/py2exe/py2exe/blob/b183301a2dec8a4e2c8eb72df1acac3934b8ec7b/py2exe/hooks.py#L17

I'm not sure if this excludes list serves to shorten the list of missing modules printed at the end (in which case dropping the line is probably fine), or if there's more to it (and maybe the line is conditionally dropped only if `windows-curses` is installed).

For reference, here's the windows-curses project: https://github.com/zephyrproject-rtos/windows-curses

**Comment by albertosottile** [comment]
Thanks for reporting this. As you might have noticed from blame, that code was just imported in the repository from SourceForge and never changed in the last 8 years. Hence, I do not know why `_curses` was explicitly added to the exclusion list. Perhaps it was not compatible with the ecosystem and the implementation of `py2exe` at that time.

My question for you would be: does the bundled executable that you created after commenting the `_curses` entry work as expected? If so, I can try to remove this module from the exclusion list, see what effect this has on the Ci, and eventually release a patch for py2exe.

**Comment by albertosottile** [comment]
> but it might be worth restoring one of the previous messages that indicated it was in the exclude list.

Are you referring to this message: `ImportError: Module '_curses' is in the "excludes" list` ? I thought this message was printed because you mentioned it in your first post. Could you tell me which message is actually printed in 0.11.1.0 ? Thanks.

**Comment by mharbison72** [comment]
> > but it might be worth restoring one of the previous messages that indicated it was in the exclude list.
> 
> Are you referring to this message: `ImportError: Module '_curses' is in the "excludes" list` ? I thought this message was printed because you mentioned it in your first post. Could you tell me which message is actually printed in 0.11.1.0 ? Thanks.

Yes, sorry for the confusion.  Prior versions explicitly mentioned the exclude list in this way (and some slightly different ways, but I dump the text buffer I had with them apparently).

The current message in 0.11.1.0 is simply `ImportError: No module named '_curses'`, which is what you'd get if something wasn't installed or similar.

**Comment by albertosottile** [comment]
I restored the former message in the linked commit and I will release this fix in the upcoming patch release. Thanks for reporting this.

**Comment by mharbison72** [comment]
Thanks!  The original report was that the curses package can't be packaged like the old py2 builds could, because it is in the exclude list.  I've manually removed it from the list for TortoiseHg builds, and have had no problems with that.  So it seems like it could be removed here too.
