### ISSUE TITLE
setuptools 62.3.2 complains about finding multiple top-level packages

### ISSUE THREAD

**Issue by Athanasius** [py2exe/py2exe#136]
Going to build [EDMC 5.4.0-beta0](https://github.com/EDCD/EDMarketConnector/tree/release-5.4.0-beta0) today I've run into:

```
> python setup.py py2exe
Git short hash: 77145831
C:\Users\Athan\Documents\Devel\EDMarketConnector\venv\lib\site-packages\setuptools\dist.py:531: UserWarning: Normalizing '5.4.0-beta0+77145831' to '5.4.0b0+77145831'
  warnings.warn(tmpl.format(**locals()))
error: Multiple top-level packages discovered in a flat-layout: ['img', 'wix', 'dump', 'L10n', 'config', 'FDevIDs', 'plugins'].

To avoid accidental inclusion of unwanted files or directories,
setuptools will not proceed with this build.

If you are trying to create a single distribution with multiple packages
on purpose, you should not rely on automatic discovery.
Instead, consider the following options:

1. set up custom discovery (`find` directive with `include` or `exclude`)
2. use a `src-layout`
3. explicitly set `py_modules` or `packages` with a list of names

To find more information, look for "package discovery" on setuptools docs.
```
In setup.py, at the py2exe level we already *do* specify both a `packages` and `includes`/`excludes`.

Any advice on resolving this and getting a working build with this (and presumably future) setuptools appreciated.

In the meantime I'll see how far back I need to roll setuptools for it to work again, we last built with `60.10.0`.

**Comment by Athanasius** [comment]
`60.10.0` is the last version that works, even `61.0.0` exhibits this issue.

**Comment by jeremyw2019** [comment]
I can confirm this as well.

**Comment by albertosottile** [comment]
Hi, thanks for reporting this... I am not sure this is something that is caused by `py2exe` or by `setuptools` on its own. Have you tried applied the solutions proposed e.g. here: https://stackoverflow.com/questions/72294299/multiple-top-level-packages-discovered-in-a-flat-layout ?

**Comment by Athanasius** [comment]
> Hi, thanks for reporting this... I am not sure whether this is something that is caused by `py2exe` or by `setuptools` on its own. Have you tried applied the solutions proposed e.g. here: [stackoverflow.com/questions/72294299/multiple-top-level-packages-discovered-in-a-flat-layout](https://stackoverflow.com/questions/72294299/multiple-top-level-packages-discovered-in-a-flat-layout) ?

Your google fu was better than mine!

Yes, adding `py_modules=[],` to the `setup()` parameters results in the build working with `setuptools==62.6.0`.  Well, except now I need to go chase down another error upon actually running the resulting .exe ....
