### ISSUE TITLE
stderr log needs modernization

### ISSUE THREAD

**Issue by mharbison72** [py2exe/py2exe#138]
The log file to which stderr is redirected in `boot_common.py` has a couple of issues that appear to have been inherited by the original py2 code from ~15 years ago.

1) Writing next to `sys.executable` will generally mean writing to `%PROGRAMFILES%`, which UAC blocks when it is turned on.  That results in losing the stderr output (unless the app is launched with Admin rights), as program output should go to `%PROGRAMDATA%`.

2) The `write()` method for the stream is supposed to return the number of characters written.  #134 addresses this.

3) It looks like the `write()` method on the redirected stream has a couple of default parameters that are non-standard, and not supplied anywhere in the codebase.  I think they can be dropped.

I ended up implementing a workaround for this in TortoiseHg[1], but it would be better to have this upstream.  Probably the trickiest part will be figuring out what subpath to write to under `%PROGRAMDATA%`.

[1] https://foss.heptapod.net/mercurial/tortoisehg/thg/-/commit/15c88bb932f18c14f5d1ff6a277ebde5d722786e

**Comment by albertosottile** [comment]
Hello, thanks for reporting this.

Re 1): I completely agree, I would change the path to either `%PROGRAMDATA` or `%APPDATA` and keep the "executable name" + ".log" file name, for the moment Any path preference?

Re 2): I plan to merge #134 soon addressing this issue.

Re 3): I am not entirely sure to what definition you refer to. If you are talking about https://github.com/py2exe/py2exe/blob/master/py2exe/boot_common.py#L55, then the only unusual parameter is `alert`, for which I could not find a definition indeed... However, I am quite against deleting it, as users might have changed this parameter in their apps and keeping it is rather harmless.

**Comment by mharbison72** [comment]
> Hello, thanks for reporting this.
> 
> Re 1): I completely agree, I would change the path to either `%PROGRAMDATA%` or `%APPDATA%` and keep the "executable name" + ".log" file name, for the moment. Any path preference?

I think `%PROGRAMDATA%`, but TBH, I've forgotten the differences between these two.  I think the tricky part to making this generic is:

1) It seems (more) reasonable to write next to the executable for things that aren't installed

2) There's usually more directory structure than just dumping it into `%PROGRAMDATA%`.  (e.g. I'm using `%PROGRAMDATA%\TortoiseHg\thgw.log`)

I guess if you agree with both of these points, the logic could be to check if `sys.executable` starts with `%PROGRAMFILES%` and if it does, strip it off and prepend `%PROGRAMDATA%` (making the directory tree of course).  That might do weird things if the `%PROGRAMFILES%` tree has extra stuff (like a `bin` directory), so maybe it's better to pass an argument that the building program can specify?

> Re 2): I plan to merge #134 soon addressing this issue.
> 
> Re 3): I am not entirely sure to what definition you refer to. If you are talking about https://github.com/py2exe/py2exe/blob/master/py2exe/boot_common.py#L55, then the only unusual parameter is `alert`, for which I could not find a definition indeed... However, I am quite against deleting it, as users might have changed this parameter in their apps and keeping it is rather harmless.

Yes.  Neither `alert` nor `fname` are passed by any internal callers that I saw, and it seems odd to me that external callers would pass that since they're probably expecting a regular stdio stream.  Mostly I was thinking that if you dropped them, you could simply `open` the log file and use it directly like I did in TortoiseHg.  But if you think you want to keep it, it's easy enough to define a proxy with that method that delegates to the stream returned by `open`, and you won't have to worry about the interface changing in the future.

**Comment by albertosottile** [comment]
Re 1): TBH I'd prefer `%APPDATA% + executablename` as this will work much better for development and non-installed software, as you correctly mentioned. I believe these two are the biggest use case for these logs, as installed SW usually have more developed ways to report error messages. 

I'd like to add that developers are free to override the stderr if they want to customize this behavior, as done in Syncplay [here](https://github.com/Syncplay/syncplay/blob/9757e618080127f8b0ae4673f9c32dbc20ada764/syncplay/utils.py#L191) for a long time.

Re 2): 
I might drop the `fname` argument as we now want to introduce more logic in how this string is evaluated, but I like the Windows alert feature, which incidentally shows the log path. I could still move the alert definition inside the method, instead of keeping it as an argument with a default value, but I still do not see the harm of having this extra argument here.

**Comment by albertosottile** [comment]
Re 2): in the end I removed both arguments. Personally, I consider this issue fixed. I will release the fixes in the upcoming patch release.

**Comment by mharbison72** [comment]
Thanks for the fix.  I think it's good enough for a debug log.
