### ISSUE TITLE
infi.systray / pkg_resources now needs `pyparsing` as well

### ISSUE THREAD

**Issue by Athanasius** [py2exe/py2exe#139]
Having resolved #136 I'm now looking at this upon running the resultant .exe:

```python
Traceback (most recent call last):
  File "EDMarketConnector.py", line 2012, in <module>
  File "EDMarketConnector.py", line 448, in __init__
  File "infi\systray\__init__.pyc", line 1, in <module>
  File "pkg_resources\__init__.pyc", line 84, in <module>
  File "pkg_resources\_vendor\packaging\requirements.pyc", line 10, in <module>
  File "pkg_resources\extern\__init__.pyc", line 52, in create_module
  File "pkg_resources\extern\__init__.pyc", line 44, in load_module
ImportError: The 'pyparsing' package is required; normally this is bundled with this package so if you get this warning, consult the packager of your distribution.
```
Upon checking, the python environment's `pkg_resources` has `pkg_resources/_vendor/pyparsing/` but that isn't included in the build's `library.zip`.

```
py2exe==0.11.1.0
infi.systray==0.1.12
```
This is with Windows 32-bit python `3.10.5` as the base.

Manually doing `zip -ru ../../../dist.win32/library.zip pkg_resources/_vendor/pyparsing` (from the venv's site-packages/) allows the .exe to run from the dist.win32 directory.

**Comment by Athanasius** [comment]
I was wondering WTF I hadn't already run into this, so re-checked with `setuptools==60.10.0` and it's not an issue, `pyparsing.py` gets included as necessary.  Back to `setuptools==62.6.0` and re-checking, and it's definitely not included.  So some change in setuptools is causing this.

**Comment by albertosottile** [comment]
Sigh... I'd like very much if they could stop adding packages to `pkg_resources` and/or if they could use a normally supported loader instead of their crazy `extern.VendorImporter` thing. Anyway, I hope that adding `pyparsing` [as in here](https://github.com/py2exe/py2exe/commit/979b7b9a88b42224e0e640f4696b66a911321a92) will solve the issue. I will give it a try when I have some spare time.

**Comment by albertosottile** [comment]
As I hoped, adding `finder.import_package("pkg_resources._vendor.pyparsing")` after https://github.com/py2exe/py2exe/blob/62ed73f5c7fea2cfe413b40063b82059fc38d312/py2exe/hooks.py#L605 fixed my local test case. Could you try the same on your system? If you can confirm this fixes also your environment, I could quickly push a fix commit on `master`. I am afraid there will be some time before the next patch release.

**Comment by Athanasius** [comment]
Yup, with `pip install setuptools==62.6.0` just run, making that edit results in a working .exe/library.zip as the latter includes `pkg_resources/_vendor/pyparsing/<files>`.

We'll need to wait on the next patch release to use this though, as we typically build on GitHub, and setting that up to patch py2exe will be a pain.

**Comment by albertosottile** [comment]
Thanks for confirming the fix, I'll see what I can do for the release.
