### ISSUE TITLE
VersionInfo and Manifest are missing from the resource table

### ISSUE THREAD

**Issue by mharbison72** [py2exe/py2exe#141]
I think this is a regression from the old python2 build, as it used to work and I didn't (purposely) change anything to omit it.  As an example, here's the py2 resources for TortoiseHg:

![image](https://user-images.githubusercontent.com/57785103/179295915-7a8d4cb2-e284-4d98-aded-393c1a91700a.png)

vs what it is for the py3 build:

![image](https://user-images.githubusercontent.com/57785103/179296125-a7b4411d-b4c8-4fa7-9373-857f9b4e3360.png)

FWIW, the manifest in py2 was `requestedExecutionLevel level="asInvoker"`, so it was the minimal thing to keep UAC happy.

**Comment by Athanasius** [comment]
All of that information shows up in my python3, py2exe-built, .exe's.  Are you actually setting those bits in the call to `setup()` in `setup.py` ?  We have:

```python
setup(
    name=applongname,
    version=appversion_str,
    windows=[
        {
            'dest_base': appname,
            'script': APP,
            'icon_resources': [(0, f'{appname}.ico')],
            'company_name': 'EDCD',  # Used by WinSparkle
            'product_name': appname,  # Used by WinSparkle
            'version': base_appversion,
            'product_version': appversion_str,
            'copyright': copyright,
            'other_resources': [(24, 1, open(f'{appname}.manifest').read())],
        }
    ],
    console=[
        {
            'dest_base': appcmdname,
            'script': APPCMD,
            'company_name': 'EDCD',
            'product_name': appname,
            'version': base_appversion,
            'product_version': appversion_str,
            'copyright': copyright,
            'other_resources': [(24, 1, open(f'{appcmdname}.manifest').read())],
        }
    ],
    data_files=DATA_FILES,
    options=OPTIONS,
    py_modules=[],
)```
and it is precisely that `windows` array's information that shows up in the `VersionInfo`, and a what we have in that `.manifest` file as the `Manifest` section.

**Comment by mharbison72** [comment]
I had some of those:

```
    extra['console'] = [
        {'script': 'contrib/hg',
         'icon_resources': [(0, 'icons/hg.ico')],
         'description': 'Mercurial Distributed SCM',
         'copyright': hgcopyright,
         'product_version': version,
         },
    ...
```

It looks like by simply adding `'version': '6.2'`, that causes the `description`, `copyright` and `product_version` to be added to the resource table as before.  Not sure why that changed, but it's good enough for me since there's a way to continue making the data available.  Thanks for the pointers.
