### ISSUE TITLE
OSerror when install py2exe

### ISSUE THREAD

**Issue by nestienn** [py2exe/py2exe#146]
With python 3.10 in windows 10 environment with admin rigths, using pip3 install py2exe , the installation failed even with --user and $TMPDIR set with rigth access.
ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: 'C:\\Users\\myuser\\AppData\\Local\\Temp\\pip-unpack-26qgj7ay\\py2exe-0.11.1.1-cp310-cp310-win_amd64.whl'
Check the permissions.
I updated "wheel" module successfully, it means that pip3 seems to execute properly.

**Comment by albertosottile** [comment]
Hello, thanks for reporting this. I am afraid this is more a bug of `pip` than of `py2exe`, given that you are unable to install the package. Quick question, though: how did you install Python? If you installed the version from the Windows Store, I'd encourage you to uninstall it and install the one from the official Python website: https://www.python.org/

**Comment by nestienn** [comment]
Hello, thanks a lot for your response. I installed succesfully other packages it’s thé reason why I opened this issue. Nervertheless I will follow your recomandation by re installing Python package. 
Nicolas 

Envoyé de mon iPhone

**Comment by albertosottile** [comment]
Closing this as most likely it is not related to `py2exe`.
