### ISSUE TITLE
py2exe无法打包包含第三方库的py文件

### ISSUE THREAD

**Issue by dhbliss** [py2exe/py2exe#148]
当我使用python自带的库进行打包时无异常，但是使用第三方库requests或psutil时，打包的文件无法打开，python版本使用的 py3.7

**Comment by Athanasius** [comment]
FTR: Google Translate says:

> When I use the library that comes with python for packaging, there is no exception, but when I use the third-party library requests or psutil, the packaged file cannot be opened, and the python version uses py3.7

**Comment by albertosottile** [comment]
@dhbliss Could you provide a minimal example to reproduce your error? This should include a test script and a freezing script (`setup.py` or `freeze`). Thanks

**Comment by albertosottile** [comment]
Closing as no further input was provided.
