### ISSUE TITLE
DeprecationWarning: the `setup.py py2exe` command line interface is deprecated

### ISSUE THREAD

**Issue by albertosottile** [py2exe/py2exe#150]
From version 0.12.0.0, the invocation of the `setup` function for `py2exe` and the usage of the `setup.py py2exe` CLI are deprecated in favor of the new `freeze` API. Documentation of the new API can be found [here](docs/py2exe.freeze.md), whereas a migration guide can be found [here](docs/migration.md).

These interfaces were deprecated because of [PEP 632](https://peps.python.org/pep-0632/) and because `setuptools` deprecated the whole `python setup.py ...` CLI (see the last paragraph [here](https://setuptools.pypa.io/en/latest/userguide/extension.html#final-remarks)).

Further information about this change can be found in issue #127.

**Comment by Athanasius** [comment]
The links for the docs are broken, being relative, which doesn't work from inside an issue.
