### ISSUE TITLE
dest_dir option in py2exe.freeze is broken

### ISSUE THREAD

**Issue by matiusz** [py2exe/py2exe#160]
According to [py2exe.freeze documentation](https://github.com/py2exe/py2exe/blob/master/docs/py2exe.freeze.md), in order to set destination directory one needs to specify "dest_dir" option. After this option doing absolutely nothing, I've checked the source code and found the following line:
`destdir = options.get("dist_dir", "dist"),`, and lo and behold, specifying "dist_dir" works. So obviously there is a mismatch between the option in the code and in the documentation.
My suggestion: obviously correct one of the parts to have the option be named consistently, but also warn the user about unexpected options parsed.

**Comment by albertosottile** [comment]
Thanks for reporting this. I apologize, I thought I had tested this with https://github.com/Syncplay/syncplay/blob/fa06378b6dbdef8ae83071fdc0853f897c735ddc/buildPy2exe.py#L696 but indeed also there the option is named `dist_dir`. 

After searching in the code base, it seems indeed the correct option name is `dist_dir` and so the typo is in the documentation. I will fix the documentation ASAP.
