### ISSUE TITLE
ModuleNotFoundError: No module named 'fcntl'

### ISSUE THREAD

**Issue by marthvon** [py2exe/py2exe#161]
Windows apparently doesn't have a 'fcntl' module. It fails to build when installed by pip and displays the error:
error: metadata-generation-failed

this is the stack trace:
File ". . \anaconda3\lib\site-packages\py2app\util.py", line 5, in <module>
          import fcntl 

Python version 3.8.8

**Comment by Athanasius** [comment]
As far as I'm aware `fcntl` just isn't a thing on Windows.

If you're trying to use it to lock a file then you have to use Windows-native file locking instead, e.g. https://github.com/EDCD/EDMarketConnector/blob/main/journal_lock.py#L97-L108

**Comment by albertosottile** [comment]
Hi, it looks like you are trying to install and use **py2app** on Windows, hence the error messages. 

> File ". . \anaconda3\lib\site-packages\py2app\util.py", line 5, in 

py2exe does not depend on `fcntl`.
