### ISSUE TITLE
py2exe.org tutorial showcases deprecated setup.py instead of freeze

### ISSUE THREAD

**Issue by novski** [py2exe/py2exe#163]
The Tutorial [here](http://www.py2exe.org/index.cgi/Tutorial) tells me how to use py2exe with a deprecated api (setup.py instead of freeze api)

How can I use freeze api? 
Can somebody give me a how to execute?

**Comment by schnitzlein** [comment]
Example Python Code Snippet:

> #!/usr/bin/env python
> 
> # native imports
> import io
> from sys import exit, stdin, stdout, stderr, platform
> import pathlib
> import sys
> import threading
> import signal
> import argparse
> from queue import Queue, Empty, Full
> import typing
> 
> #import pandas as pd
> 
> 
> sys.path.insert(0, "lib.zip")
> 
> if __name__ == '__main__':
>     #x = pd.DataFrame()
>     print("hello")

And the builder setup:

> # newer version usage no usage of setuptools
> from py2exe import freeze
> freeze(
>     console=['hello.py'],
>     windows=[],
>     zipfile='library.zip',
>     options = {
>         "packages": [],
>         "includes": [],
>         },
>     data_files=None,
>     version_info={}
> )
>

**Comment by albertosottile** [comment]
@schnitzlein The freeze example seems fine, but you are importing a lot of standard library modules that are actually not needed, so I would remove them. Something like
```python
if __name__ == '__main__':
    print("hello")
```
should suffice.

**Comment by schnitzlein** [comment]
good point, I remove it in the entry above.

**Comment by albertosottile** [comment]
Closing this as the question was answered by @schnitzlein. Thanks
