### ISSUE TITLE
freeze module of py2exe does not support building a service anymore

### ISSUE THREAD

**Issue by caesimsol** [py2exe/py2exe#178]
Hello dear py2exe developers!

I have tried to build an service module with the new proposed way of using the freeze() module of py2exe but I got the error which states:

TypeError: freeze() got an unexpected keyword argument 'service'

The Python version used is 3.11.

The definition is:
freeze(
        ... ,
        # console=[{...}] ,
        zipfile = 'limit_server.dll' ,
        service=[{
            'modules':'server'#,
            #'icon_resources':[(1, 'icon.ico')]
        }],
        ... ,
)

Is there any workaround? Has this feature been dropped?

Best regards,

Svetoslav Inkolov

**Comment by mbokil** [comment]
I found that you can still get this to work with services but it is missing in the documentation. I will see if I can add it to the migration document.

```
myservice = Target(
   script="myservice.py"
)

freeze(
   console = [myservice],
   version_info={'version':'1.0.0'}
)
```

**Comment by albertosottile** [comment]
@caesimsol As you noted the feature does not work, it probably never worked properly with Python 3.x, and was officially dropped two major versions before. There is no workaround to build directly a COM server from `py2exe`, I am sure you can find some workaround to build a service starting from a console binary.

@mbokil Thanks for the workaround but, with this you would just build a console binary. Creating a service still requires extra work that has to be carried out manually with other tools. Therefore, I would advice not to add this in the documentation of `py2exe`.

**Comment by mbokil** [comment]
@albertosottile I think you might have misread the posters question. They wanted to know if the freeze API supports building a console based service. It clearly does support this feature I used it just the other day and then packaged up my project using Inno Setup and distributed the service to client Windows systems. I suggest keeping an example of building a console service like I listed above. It was hard to figure out how to do it with the freeze API but it definitely works. Thanks for you work on this project. I deployed my Windows service to 56K machines in our company. Zero reported defects.

**Comment by albertosottile** [comment]
I am sorry, but I do not understand. What you are building is a console application, a binary that you can run from the terminal. What @caesimsol is asking for, and what the old `service` argument was doing is generating a [Windows Service](https://en.wikipedia.org/wiki/Windows_service) directly. `py2exe` does not support this anymore. However, you can of course build a console up and pack it/deploy it as a service manually or with other tools, e.g. [NSSM](https://nssm.cc/). 

Packaging a console application is of course supported and, I think, well documented in the freeze API documentation https://github.com/py2exe/py2exe/blob/master/docs/py2exe.freeze.md . I am not sure in what your example differs from the existing documentation.

> Thanks for you work on this project. I deployed my Windows service to 56K machines in our company. Zero reported defects.

Stories like these are always appreciated, thank you for having reported this here.

**Comment by caesimsol** [comment]
I have to comment that with this definition in Python 3.10:

    setup(
        data_files = Mydata_files,
        name='LimitLS',
        description = 'LIMIT License Server 2023',
        version=version_string,
        maintainer='CAE Simulation & Solutions GmbH',
        author='Michael Lindner, Svetoslav Inkolov',
        options={"py2exe": {"compressed": 1,
                              "optimize": 2,
                              "includes": includes,
                              "excludes": excludes,
                              "packages": packages,
                              "dll_excludes": dll_excludes,
    #                          "dll_excludes": dll_excludes_win_10,
                              "bundle_files": 3,
                              "dist_dir": "service",
                              "xref": False,
                              "skip_archive": False,
                              "ascii": False,
                              "custom_boot_script": '',
                             }
                  },
        zipfile = 'limit_server.dll',
        version_info={'version':version_string,
                      'description':'LIMIT License Server 2023',
                      'product_name':'LimitLS',
                      'copyright':'© CAE Simulation & Solutions GmbH'},
        #windows=[{
        #console=[{
        service=[{
            'modules':'server'#,
            #'icon_resources':[(1, 'icon.ico')]
        }]
    
    )

I got an service file named "server.exe" as a console module with a zipfile 'limit_server.dll' and it works perfectly fine.

The service was then installed with:

@echo off
set LLSDIR=%~dp0
service\server.exe -install
sc config LimitLS start= auto

In Python 3.11 this is unfortunately not possible anymore :'-(

**Comment by caesimsol** [comment]
I just wanted to add that in Python 3.10 it was possible to set up or assign a value to the service parameter:

def patch_distutils():
    import distutils.dist
    import distutils.core
    import distutils.command
    import sys
    from . import distutils_buildexe

    class Distribution(distutils.dist.Distribution):

        def __init__(self, attrs):
            self.ctypes_com_server = attrs.pop("ctypes_com_server", [])
            self.com_server = attrs.pop("com_server", [])
            self.service = attrs.pop("service", [])
            self.windows = attrs.pop("windows", [])
            self.console = attrs.pop("console", [])
            self.isapi = attrs.pop("isapi", [])
            self.zipfile = attrs.pop("zipfile", "library.zip")

            distutils.dist.Distribution.__init__(self, attrs)

    distutils.core.Distribution = Distribution

    distutils.command.__all__.append('py2exe')

    sys.modules['distutils.command.py2exe'] = distutils_buildexe

and in the Python 3.11 variant it is not possible anymore to assign something to the service parameter:

    console_targets = runtime.fixup_targets(console, "script")
    for target in console_targets:
        target.exe_type = "console_exe"

    windows_targets = runtime.fixup_targets(windows, "script")
    for target in windows_targets:
        target.exe_type = "windows_exe"

    # support the old dictionary structure with a global 'py2exe' key
    if 'py2exe' in options:
        options = options['py2exe']

    runtime_options = Namespace(
                        compress = options.get("compressed", 0),
                        unbuffered = options.get("unbuffered", 0),
                        optimize = options.get("optimize", 0),
                        includes = options.get("includes", []),
                        excludes = options.get("excludes", []),
                        packages = options.get("packages", []),
                        dll_excludes = options.get("dll_excludes", []),
                        bundle_files = options.get("bundle_files", 3),

                        script = console_targets + windows_targets,
                        service = [],
                        com_servers = [],

                        destdir = options.get("dist_dir", "dist"),
                        libname = zipfile,

                        verbose = options.get("verbose", 0),
                        report = False,
                        summary = False,

                        data_files = data_files,

                        version_info = {},

                    )

**Comment by urishab** [comment]
Hi Alberto
I'm playing around with updating to Python3.11 and updating my py2exe package as well. 
I found that the current version does not support building Windows services with the new freeze interface.

However when I actually try this I can build a working Windows service using py2exe 0.14.0.0.
I can either use the old interface which just works (using distutils)

Or I can use the new interface "freeze" which doesn't work out of the box.
I had the AI fix it and it did by slightly modifying __init__.py.
I don't understand the fix but again I'm getting a working native Windows service.

Is there a good reason NOT to restore service functionality in py2exe? At least for Python 3.11?

I see you're commenting that it never REALLY worked under Python3. What do you mean by that?

I did run into another quirk during this which is if my service was not digitally signed it failed to start.
I'm not sure if this is global or new for Windows11 or whatever but thought it might be worth mentioning.

Here's the fixed "freeze" function for your reference

```
def freeze(console=[], windows=[], service=[], data_files=None, zipfile="library.zip", options={}, version_info={}):
    """Create a frozen executable from the passed Python script(s).

    Arguments:
        console (list of dict): paths of the Python files that will be frozen
            as console (CLI) executables. See below for the target dict syntax.
        windows (list of dict): paths of the Python files that will be frozen
            as windows (GUI) executables. See below for the target dict syntax.
        data_files (list): non-Python files that have to be added in the frozen
            bundle. Each element of the list is a tuple containing the destination
            path in the bundle and the source path of the data files.
        zipfile (str): target path of the archive that will contain all the Python
            packages and modules required by the frozen bundle.
            If this parameter is set to `None`, the archive will be attached
            to the target executable file.
        options (dict): options used to configure and customize the bundle.
            Supported values are listed below.
        version_info (dict): version strings and other information can be attached
            to the Windows executable file by configuring this dictionary.
            Supported values are listed below.

    Target dictionaries (to be used for `console` or `windows`):
        script (str): path of the Python module of the executable target.
        dest_base (str): optional, directory and basename of the executable.
            If a directory is contained, must be the same for all targets
        bitmap_resources (list): list of 2-tuples `(id, pathname)`.
            Bitmap files added in the bundle.
        icon_resources (list): list of 2-tuples `(id, pathname)`
            Icon used for the executable.
        other_resources (list): list of 3-tuples `(resource_type, id, datastring)`
            Other files added in the bundle.
        version_info (dict): optionally specifies version information for a given binary.
            Supported values are listed below.

    Options (`options`):
        includes (list): list of modules to include in the bundle.
        excludes (list): list of modules to exclude from the bundle.
        packages (list): list of packages to include in the bundle. Note: this option
            is NOT recursive. Only the modules in the first level of the package will
            be included.
        dll_excludes (list): list of DLLs to exclude from the bundle.
        dist_dir (str): target path of the bundle, default `dist`.
        compressed (int): if `1`, create a compressed destination library archive.
        unbuffered (int): if `1`, use unbuffered binary stdout and stderr.
        optimize (int): optimization level of the Python files embedded in the bundle
            default: `0`. Use `0` for `-O0`, `1` for `-O`, `2` for `-OO`.
        verbose (int): verbosity level of the freezing process, default `0`. Supported
            levels are `0--4`.
        bundle_files (int): select how to bundle the Python and extension DLL files,
            default `3` (all the files are copied alongside the frozen executable).
            See below for further information on this parameter.

    Bundle files levels (`bundle_files`): The py2exe runtime *can* use extension module
        by directly importing the from a zip-archive - without the need to unpack them
        to the file system. The bundle_files option specifies where the extension modules,
        the python DLL itself, and other needed DLLs are put.
        bundle_files == 3: Extension modules, the Python DLL and other needed DLLs are
            copied into the directory where the zipfile or the EXE/DLL files
            are created, and loaded in the normal way.

    **WARNING**: the following values are not supported in Python 3.12+! See
    https://github.com/py2exe/py2exe/issues/225 for further details.

        bundle_files == 2: Extension modules are put into the library ziparchive and loaded
            from it directly. The Python DLL and any other needed DLLs are copied into the
            directory where the zipfile or the EXE/DLL files are created, and loaded
            in the normal way.
        bundle_files == 1: Extension modules and the Python DLL are put into
            the zipfile or the EXE/DLL files, and everything is loaded without unpacking to
            the file system.  This does not work for some DLLs, so use with
            caution.
        bundle_files == 0: Extension modules, the Python DLL, and other needed DLLs are put
            into the zipfile or the EXE/DLL files, and everything is loaded
            without unpacking to the file system.  This does not work for
            some DLLs, so use with caution.

    Version information (`version_info`): Information passed in this dictionary are attached
        to all frozen executables and displayed in their Properties -> Details view.
        If you need to specify different version information for each of the frozen binaries
        you should add `version_info` dictionary to each of the `windows` and `console` targets.
        Supported keys:
        version (str): version number
        description (str): -
        comments (str): -
        company_name (str): -
        copyright (str): -
        trademarks (str): -
        product_name (str): -
        product_version (str): -
        internal_name (str): -
        private_build (str): -
        special_build (str): -

    Support limitations:
        `bundle_files <=2`: these settings do not work in Python 3.12+. See https://github.com/py2exe/py2exe/issues/225
            for further details. In general, these values are supported only for packages in the Python
            standard library. Issues occurring with external packages and lower values
            of `bundle_files` will not be investigated.
        `zipfile = None`: is not actively supported. Issues occurring when this
            option is used will not be investigated.
        Please use CPython from python.org: freezing from non-standard CPython installations,
            such as `conda` or Windows Store is not supported.
        `venv`: freezing from a virtual environment can cause unexpected errors for some
            scripts. We encourage the use of Docker Windows Containers for isolating
            the freezing environment.

    """
    console_targets = runtime.fixup_targets(console, "script")
    for target in console_targets:
        target.exe_type = "console_exe"
        target.version_info = _fixup_version_info(getattr(target, "version_info", None) or version_info)

    windows_targets = runtime.fixup_targets(windows, "script")
    for target in windows_targets:
        target.exe_type = "windows_exe"
        target.version_info = _fixup_version_info(getattr(target, "version_info", None) or version_info)

    service_targets = runtime.fixup_targets(service, "modules")
    for target in service_targets:
        target.exe_type = "service"
        target.version_info = _fixup_version_info(getattr(target, "version_info", None) or version_info)

    # support the old dictionary structure with a global 'py2exe' key
    if 'py2exe' in options:
        options = options['py2exe']

    runtime_options = Namespace(
                        compress = options.get("compressed", 0),
                        unbuffered = options.get("unbuffered", 0),
                        optimize = options.get("optimize", 0),
                        includes = options.get("includes", []),
                        excludes = options.get("excludes", []),
                        packages = options.get("packages", []),
                        dll_excludes = options.get("dll_excludes", []),
                        bundle_files = options.get("bundle_files", 3),

                        script = console_targets + windows_targets,
                        service = service_targets,
                        com_servers = [],

                        destdir = options.get("dist_dir", "dist"),
                        libname = zipfile,

                        verbose = options.get("verbose", 0),
                        report = False,
                        summary = False,

                        data_files = data_files,

                    )

    level = logging.INFO
    logging.basicConfig(level=level)

    builder = runtime.Runtime(runtime_options)
    builder.analyze()
    builder.build()

```

**Comment by albertosottile** [comment]
Hi @urishab, thanks for the investigation and the proposed patch to the `freeze` API.

> Is there a good reason NOT to restore service functionality in py2exe? At least for Python 3.11?

I think the main reason is what I stated two years ago. Since I forked the "py2exe for Python 3.x" repo, in 2019, I have never tested this feature and I have never received reports from users that this feature was functioning properly. Worse, I never even properly read the code that pertains to this feature. This is because I always had limited capacity to maintain this project (even more limited lately, as I am sure you had noticed), and so I focused on its core parts. The ultimate goal in the back of my head was always to remove these niche and untested features, such as building a service or a COM server.

So, I trust you can see why I am reluctant to officially reintroduce this ancient, unmaintained, and untested feature. Despite this, as you noticed, I still have not removed this code (yet). So, feel free to use your patched `__init__.py` file until it breaks. Hope this message answered your questions, if not, feel free to further reply here.

**Comment by urishab** [comment]
Hi @albertosottile 

I plan to continue to use the __init__.py hack. I assume it will continue to work until I'm forced to upgrade from Python 3.11 which could be a while.

I understand you're hesitant to support this feature and add a kind of "future burden".
I need this feature and I see a couple of people on this thread who need it as well.

I'm not sure if this feature works on newer versions of Python or not.
If you like I can write a test for this and this way it will at least be tested and I can test it on the latest supported Python package.

As for future maintaining I think it's always a risk using py2exe as it might break at some point in the future (and with future updates).

If it were supported by all current Python versions would you bring the interface back formally?

**Comment by albertosottile** [comment]
I'd welcome a PR that reintroduces the feature properly (including documentation) and also adds a functional test that verify the service correctly runs (this might be quite tricky in GitHub Actions). If the test covers the feature properly and passes on all the supported Python versions, I can consider restoring the interface.

**Comment by urishab** [comment]
I sent a PR #245 for this functionality

Thanks
