### ISSUE TITLE
Packages with .libs directories result in don't work

### ISSUE THREAD

**Issue by zobac** [py2exe/py2exe#181]
Python version - 3.10.8 in a virtual environment

matplotlib - 3.7.1
pyzmq - 3.7.1
scipy - 1.10.1

I'm using py2exe.freeze(), but the problem also occurs when using the old distutils.setup() method.

The packages above include a lib/site_packages/_packagename_.libs directory, which include .dll files those packages use. Py2exe doesn't include these directories in the .zip file, which results in those packages failing to import when the executable is run. If I inject those directories into the .zip file (a strategy that has worked in the past for other non python files), they still aren't found when the executable is run. Including those .dlls in the data_files list doesn't help, nor does including the entire _packagename_.libs directories in the base directory.

The error message is `The system cannot find the path specified: 'path\\to\\dist\\modules.zip\\matplotlib.libs'`, which makes some sense, given that modules.zip isn't a directory.

If I downgrade matplotlib to 3.6 there is no matplotlib.libs directory, and that package imports fine in the executable, but then pyzmq fails. I'm unable to downgrade that package to a version that doesn't include a pyzmq.libs directory. 

I see that you've dealt with this issue previously for scipy, so I suspect that that package will actually import. My program doesn't get that far, so I can't say for sure. 

Is there something I'm missing? Is this a consequence of updated packaging practices?

**Comment by zobac** [comment]
I'm working on updating the MPL hook to patch the _delvewheel_init_patch_1_3_3 function, based on the patch you implemented for scipy. It seems to work, but now I'm hitting a similar issue with finding "mpl-data".  Once I resolve these issues I'll make a pull request.

**Comment by zobac** [comment]
Ok, I've got mpl working now.  Had to add a hook for mpl_toolkits as well. Not sure if I handled versions < 3.7.0 properly though.

Is there an easy way to inject add custom hooks at runtime? It feels like this problem is going to come up more often as more packages move to storing their required .dlls in an adjacent .libs directory.

**Comment by zobac** [comment]
Ok, I submitted a pull request with the fixes for matplotlib >= 3.7.0 and an added hook for mpl_toolkits when matplotlib >= 3.7.0.

To handle other packages I was having issues with I created my own hooks file where I define hooks for babel >= 2.8.0 and pyzmq >= 23.0.0 and then in my setup file I import py2exe.hooks and punch my hooks into the module.  Not the most elegant solution, but it works.

I can add my custom hooks to py2exe.hooks.py if you want.

**Comment by albertosottile** [comment]
Thanks for the PR, I reviewed it just now. Out of curiosity: why does a messaging library like `pyzmq` depend on `matplotlib`? In any case, if you think your `babel` hook is functional, feel free to add it to the PR as well.

**Comment by zobac** [comment]
Sweet. I'll implement the requested changes in the next couple days. 

Just to clarify: pyzmq doesn't depend on matplotlib. The problem with all of these is that the devs are using [delvewheel](https://pypi.org/project/delvewheel/) for packaging, and delvewheel puts the required .dll files in an adjacent package.libs directory.

**Comment by albertosottile** [comment]
Fixed in 0.13.0.1 . Thanks for your contribution!
