### ISSUE TITLE
Link on the py2exe wiki page does not go anywhere

### ISSUE THREAD

**Issue by ThomasEwaldETH** [py2exe/py2exe#183]
Hello there!
First, thanks for the great program!
I just noticed a minor detail: The link on the py2exe [wiki page (installation)](https://pypi.org/project/py2exe/), which says "Use the py2exe.freeze function as documented [here](https://pypi.org/project/py2exe/docs/py2exe.freeze.md)." does not lead anywhere.
Best regards and have a nice day!
Thomas

**Comment by albertosottile** [comment]
Thank you for this issue, This is patched in the `develop` branch and will be fixed in the next release.

**Comment by albertosottile** [comment]
Closing this as duplicate of #162.
