### ISSUE TITLE
Py_OptimizeFlag not set correctly during Python initialization

### ISSUE THREAD

**Issue by ydder007** [py2exe/py2exe#186]
Hi there,

we recently switched to Python 3.11 / `py2exe 0.13.0.0` and noticed the optimization Flag is not set correctly in our production environment when executing external Python scripts within our application.

I tracked the issue down to the [latest changes to the Python initialization](https://github.com/py2exe/py2exe/commit/adfbd51a74718da4ec5cc74a7ecb90743d397759#diff-37b168349140aaba93d1aeedbd7350d12eca1aa7b6a1e3ccf24c3dedddbad6a1) in `start.c`.

It looks like the `PyConfig_InitIsolatedConfig(&config)` command does not take the previously set `Py_OptimizeFlag` into account when initializing the config.

I did a quick fix and added `config.optimization_level = p_script_info->optimize;` as a workaround until we get an official py2exe release.

**Comment by albertosottile** [comment]
Thanks for noting this. Looking at the old code, it is not clear to me how this flag was honored before. I can see when it is used when loading the Python library from memory (`set_vars`) but not when loading it from the disk (`bundle_files==3`). 

I can implement your fix and I guess I can extend it to the other flags which are also ignored in this case.

**Comment by albertosottile** [comment]
Fixed in 0.13.0.2
