### ISSUE TITLE
Simple pygame example tries to lookup files inside of `library.zip`

### ISSUE THREAD

**Issue by Helveg** [py2exe/py2exe#190]
Packaging the following code (in `test.py`):

```
import pygame

pygame.init()
fullscreen = pygame.display.get_desktop_sizes()[0]
surface = pygame.display.set_mode(fullscreen, pygame.FULLSCREEN)
clock = pygame.time.Clock()
running = True
while running:
    clock.tick(60)
    events = pygame.event.get()
    pygame.display.update()
pygame.quit()
```

using this `setup.py` and the command `python setup.py`:

```
from py2exe import freeze

freeze(windows=[{"script": "test.py"}])
```

Leads to the following error log when I run the executable:

```
Traceback (most recent call last):
  File "test.py", line 1, in <module>
  File "pygame\__init__.pyc", line 38, in <module>
  File "<frozen os>", line 1119, in add_dll_directory
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\pwd06\\git\\my-app\\dist\\library.zip\\pygame'
```

Versions:

```
py2exe 0.13.0
pygame 2.5.0
Python 3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)] on win32
Windows 11
```

The path `C:\\Users\\pwd06\\git\\my-app\\dist\\library.zip\\pygame` "exists"; `library.zip` is a ZIP folder, and inside of it is a record for the `pygame` directory; I do not think however that you can just directly refer to files/folders inside of zip files as a path? Perhaps that's a newer Windows function I'm unaware of :)

**Comment by albertosottile** [comment]
Is there a way to instruct `pygame` to store this special folder in a different path? The easiest way would be to do so and store it alongside the `library.zip` file instead of inside it, e.g. `C:\\Users\\pwd06\\git\\my-app\\dist\\pygame`

**Comment by Helveg** [comment]
Hmm, how come `pygame` is using the `library.zip` path as a reference? Might that be because of some of the `__file__` attributes pointing there, or it being the current working directory or something? 

What I'm guessing `pygame` is trying to do is locate a file/directory relative to some of its source files? This doesn't seem like an entirely uncommon or invalid thing for `pygame` to attempt. There's even the stdlib Python module [`importlib.resources`](https://docs.python.org/3/library/importlib.resources.html) for it.

Any thoughts on supporting access to resources inside the package directories? I'll see if I can make a reproducer using Python stdlib mechanisms.

**Comment by albertosottile** [comment]
I gave a look at the `pygame` initialization sequence and it looks quite complicated (understandably so). I would suggest to use PyInstaller as it appears the maintainers of `pygame` provide a hook for this software.
