### ISSUE TITLE
Impossible to specify different version info for each of the binaries with the new freeze API.

### ISSUE THREAD

**Issue by lukaszgo1** [py2exe/py2exe#193]
With the old setuptools based way of freezing executables, running the `setup.py` similar to the one below resulted in different version and description for each of the frozen binaries.
```python
from setuptools import setup
import py2exe


setup(
    console=[
        {"script": "bin1.py", "description": "Binary 1", "version": "22.1.6"},
        {"script": "bin2.py", "description": "Binary 2", "version": "2.3.4"}
    ]
)

```

This example is obviously artificial - we were using similar pattern when freezing NVDA, at least some parts of version info is different for each binaries we're freezing. While with the new freeze API it is possible to specify `version_info` for all of the frozen binaries, it seems impossible to make it different for each one.
@albertosottile  Would you be able to  tell if the change was intentional, and if it was what was the reasoning behind it? Assuming this was not intended would you be open to a PR reintroducing the behavior. While this is not a show stopper for NVDA it would be nice not to change version info for our binaries unnecessarily. In terms of design I'd imagine adding additional `version_info` dictionary to each `windows` and `console` target should offer the needed flexibility.

**Comment by albertosottile** [comment]
I was not aware of this use case. I do not think the breaking was intentional, but rather done during the simplification of the `freeze` API  and the cleanup of the old code (I know for a fact that the `version_info` dictionary was not working with `setup`, despite being advertised in the documentation).

Anyway, if you are willing to prepare a PR that reintroduces the old behavior and does not break the new API, I am willing to review and merge it. My main concern is what to do with the `version_info` dictionary when these extra keys are passed in the executable dictionaries.

**Comment by lukaszgo1** [comment]
> My main concern is what to do with the `version_info` dictionary when these extra keys are passed in the executable dictionaries.


I imagine that for most of the projects using py2exe the global `version_info` dictionary is sufficient, so it should be the default way of specifying version info. If for some use case it is necessary to specify it differently for one binaries, we can safely assume it can be specified for all of them. In other words what I propose would be to use values from the passed `version_info` by default, and if for a given `windows` or `console` target there is a dictionary called `version_info` values from it should be used. I can obviously imagine a more complex implementation which somehow uses the keys for the per binary dictionaries when present, and version info values from the global dictionary for missing ones, but that is probably overkill. Would this work for you?

**Comment by albertosottile** [comment]
I agree with the assumption and the proposed implementation. I would appreciate if you could also add the appropriate documentation for the feature in https://github.com/py2exe/py2exe/blob/745fd7e8b901ef1c3d692a3588549d4ed50a265a/py2exe/__init__.py#L31
