### ISSUE TITLE
PYTHONIOENCODING is ignored

### ISSUE THREAD

**Issue by datadestroyd** [py2exe/py2exe#196]
I am trying to set the IO encoding of a console application to UTF-8 by setting the environment variable PYTHONIOENCODING. However, after the script is compiled with py2exe, the variable is ignored. Why is that and how can I change that?

**Comment by albertosottile** [comment]
Unfortunately, setting these variables in not supported by `py2exe`. If you really must change this, you would need to alter the Python initialization code in https://github.com/py2exe/py2exe/blob/master/source/start.c and recompile the project on your PC.
