### ISSUE TITLE
Failure to import zipextimporter with error "No module named '_memimporter'"

### ISSUE THREAD

**Issue by sdbbs** [py2exe/py2exe#204]
I have been messing with this for the past couple of days:

* https://stackoverflow.com/questions/78182723/does-memimporter-still-exist-in-py2exe
* [mingw-w64-x86_64-python-py2exe seems broken - _memimporter.pyd missing · Issue #20382 · msys2/MINGW-packages](https://github.com/msys2/MINGW-packages/issues/20382)

... and finally installed Python 3.11 via Microsoft Store, and tried this:

```lang-none
C:\WINDOWS\system32>python3 --version
Python 3.11.8

C:\WINDOWS\system32>python3 -m pip install py2exe
Collecting py2exe
  Downloading py2exe-0.13.0.1-cp311-cp311-win_amd64.whl.metadata (7.3 kB)
Collecting cachetools (from py2exe)
  Downloading cachetools-5.3.3-py3-none-any.whl.metadata (5.3 kB)
Collecting pefile (from py2exe)
  Downloading pefile-2023.2.7-py3-none-any.whl.metadata (1.4 kB)
Downloading py2exe-0.13.0.1-cp311-cp311-win_amd64.whl (154 kB)
   ---------------------------------------- 154.6/154.6 kB 1.9 MB/s eta 0:00:00
Downloading cachetools-5.3.3-py3-none-any.whl (9.3 kB)
Downloading pefile-2023.2.7-py3-none-any.whl (71 kB)
   ---------------------------------------- 71.8/71.8 kB ? eta 0:00:00
Installing collected packages: pefile, cachetools, py2exe
Successfully installed cachetools-5.3.3 pefile-2023.2.7 py2exe-0.13.0.1

C:\WINDOWS\system32>python3 -m pip install py2exe

C:\WINDOWS\system32>python3 -c 'import zipextimporter'
  File "<string>", line 1
    'import
    ^
SyntaxError: unterminated string literal (detected at line 1)

C:\WINDOWS\system32>python3 -c "import zipextimporter"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\sd\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\zipextimporter.py", line 51, in <module>
    import _memimporter
ModuleNotFoundError: No module named '_memimporter'
```

So - is `_memimporter` still a thing or not? The page I took it from, https://www.py2exe.org/index.cgi/TroubleshootingImportErrors has last edit in 2011, so I cannot really tell ... If it is still a thing, how do I do `import _memimporter` and `import zipextimporter`?

-----

EDIT: note that the MINGW64 package build got fixed 2024-03-21, and now there *is* a `_memexporter.pyd` in that packaging of py2exe (`mingw-w64-x86_64-python-py2exe`); the maintainer there noted in https://github.com/msys2/MINGW-packages/issues/20382#issuecomment-2012806757 : 

> I found another workaround. I renamed setup_zipextimporter.py to setup.py and build zipextimporter wheel file. It has the _memimporter pyd file.

It seems currently the vanilla Python 3 Windows build of py2exe is still broken as described above; maybe the above will help to get the vanilla build fixed as well?

**Comment by AraHaan** [comment]
For me I manually embed python and am looking into using ``zipextimporter`` to load pyd files from my site-packages that is specifically ``aiohttp``, ``frozenlist``, ``multidict``, and ``yarl``.

However the issue is, does ``zipextimporter`` work for python 3.12 yet?

**Comment by albertosottile** [comment]
@sdbbs `_memimporter` as a separate package is **not** a thing anymore. If you want to play with `zipextimporter` directly, I would suggest to use the fork from SeaHOH https://github.com/SeaHOH/memimport.

@AraHaan `py2exe` is not compatible with Python 3.12 yet and will not be compatible soon... see #191 for further information

**Comment by AraHaan** [comment]
@albertosottile I did make a local version that works for 3.12, 3.13, and 3.14 though but pulls in some of the private symbols when building for 3.13+ that is copy pasted exactly from ``import.c`` because they are: ``static``/``static inline``.

**Comment by albertosottile** [comment]
I created a poll about this topic here https://github.com/py2exe/py2exe/discussions/246.
