### ISSUE TITLE
`setuptools.dep_util` is deprecated and will be removed soon. Alternative suggested is `setuptools.modified`.

### ISSUE THREAD

**Issue by abravalheri** [py2exe/py2exe#208]
https://github.com/py2exe/py2exe/blob/4e7b2b2c60face592e67cb1bc935172a20fa371d/py2exe_setuptools.py#L10

This is the warning currently in place
https://github.com/pypa/setuptools/blob/v69.5.1/setuptools/dep_util.py#L5-L16.

**Comment by seanbudd** [comment]
Hi - this is now broken with setuptools 70 which just has been released, now you must pin setuptools to v69.5.1

https://setuptools.pypa.io/en/stable/history.html#deprecations-and-removals

**Comment by dpy013** [comment]
cc @albertosottile

**Comment by lazka** [comment]
I've created a PR ->#211
