### ISSUE TITLE
No linux or source distribution offered of pypi of version 0.13

### ISSUE THREAD

**Issue by GuillaumeFromage** [py2exe/py2exe#209]
Hi,

I can't install py2exe from pip install, it fails saying there is no version compatible with python 3.11 on debian 12/bookworm. The installer sees the version 0.12.0, 0.12.0.1 and 0.12.0.2 (0.12.0.0 Requires-Python >=3.7, <3.11; 0
.12.0.1 Requires-Python >=3.7, <3.11; 0.12.0.2 Requires-Python >=3.7, <3.11). On the repo at https://pypi.org/simple/py2exe/ , I can see that there are only windows based wheels offered, which might be the reason ? Is there a workaround ? 

Thanks.

**Comment by albertosottile** [comment]
This software can only run on Windows. There are alternatives for Linux, e.g. PyInstaller.
