### ISSUE TITLE
Error when building exe

### ISSUE THREAD

**Issue by build-agent** [py2exe/py2exe#41]
Hi @albertosottile, while using py2exe I encountered the following error and don't really understand what causing the error:
**error: [WinError 3] The system cannot find the path specified: ''**

Any idea what path it cannot find?

I am running Python version 3.7.6.
Here is my setup.py file: [setup.py.zip](https://github.com/albertosottile/py2exe/files/4200825/setup.py.zip)

Here is the output from running python setup.py py2exe: [py2exe-out.zip](https://github.com/albertosottile/py2exe/files/4200833/py2exe-out.zip)

Thank you

**pip list:**
argh                         0.26.2
backcall                     0.1.0
backports.ssl-match-hostname 3.2a3
blinker                      1.4
certifi                      2019.11.28
certsrv                      2.1.1
cffi                         1.14.0
chardet                      3.0.4
Click                        7.0
colorama                     0.4.3
cryptography                 2.8
decorator                    4.4.1
Flask                        1.1.1
greenlet                     0.4.15
idna                         2.8
ipython-genutils             0.2.0
itsdangerous                 1.1.0
jedi                         0.16.0
Jinja2                       2.11.1
MarkupSafe                   1.1.1
ntlm-auth                    1.4.0
numpy                        1.18.1
parso                        0.6.1
pathtools                    0.1.2
pickleshare                  0.7.5
Pillow                       7.0.0
pip                          20.0.2
prompt-toolkit               3.0.3
py2exe                       0.9.3.2
pycparser                    2.19
Pygments                     2.5.2
pyOpenSSL                    19.1.0
PySocks                      1.7.1
pythonping                   1.0.8
pytz                         2019.3
pywin32                      227
PyYAML                       5.3
requests                     2.22.0
requests-ntlm                1.1.0
setuptools                   41.2.0
six                          1.14.0
traitlets                    4.3.3
urllib3                      1.25.8
watchdog                     0.10.2
wcwidth                      0.1.8
Werkzeug                     1.0.0
win-inet-pton                1.1.0
wxPython                     4.0.7.post2

**Comment by build-agent** [comment]
Found what causing the error. In runtime.py line #535 there is the following statement:
                os.makedirs(os.path.dirname(extdlldir), exist_ok=True)

extdlldir is set to 'dist', so calling os.path.dirname(extdlldir) returns an empty string and calling os.makedirs with empty string throws WinError 3.

I added extra check before calling os.makedirs like this to solve the error:
            if os.path.dirname(extdlldir) != '':
                os.makedirs(os.path.dirname(extdlldir), exist_ok=True)

**Comment by albertosottile** [comment]
That's great, thank you for investigating this. If you could open a Pull Request with this fix, that would be great. Otherwise, I will probably do this in the upcoming release.

**Comment by albertosottile** [comment]
I think this is the same issue addressed by #43. The problem with both this issue and that PR is that it is not clear to me which package is causing this error to appear. If you could narrow down your pip list and find the package resposible for this issue, it would be great.

**Comment by albertosottile** [comment]
This should be fixed in 0.10.1.0, I would encourage you to try again with this release.
