### ISSUE TITLE
Bundling too many data files crashes compilation

### ISSUE THREAD

**Issue by PinkDev1** [py2exe/py2exe#52]
I'm trying to compile my project "Terraria-Colourfull-Chat", but problem 1) is it depends on an Auto Hot Key wrapper. Previously, I had used pyinstaller to make the executable, but it ended up being to big so I decided to try to use py2exe.
Now comes the main issue.
The AHK files that needed to be added into the app have to be added as "data files". Because py2exe doesn't have it's own way of recursively importing the contents of a folder, I made my own!
After 3 hours, it's finally finished, and it works flawlessly. Except, py2exe doesn't like it when you give it **46** different data files, with the entire `data_files` parameter being **7752** characters long.

When I try to build it, I get the following error:
```
running py2exe
Traceback (most recent call last):
  File "c:\Users\-REDACTED USERNAME-\Documents\GitHub\terrariaColorfullChat\python37venv\lib\site-packages\py2exe\mf3.py", line 706, in __code__
    optimize=self.__optimize__)
  File "__SCRIPT__.pyc", line 6
    <<<<<<< Updated upstream
     ^
SyntaxError: invalid syntax
```

# Environment
python 3.7.7
py2exe 2019.4.18
Windows 10.0.19041 Build 19041

# Replicate
Attempt to compile the [development branch of my project](https://github.com/PinkDev1/Terraria-Colourfull-Chat/tree/development), with my custom `setup.py`

```
git clone --branch development https://github.com/PinkDev1/Terraria-Colourfull-Chat.git
cd Terraria-Colourfull-Chat
py 3.7 -m pip install -r requirements.txt
py -3.7 setup.py py2exe
```

Make sure to replace the current path in line 54 of setup.py with the actual path of where you have the AHK Wrapper's `templates` folder is. Although it is not explicitly in the instructions above, I recommend installing the requierements.txt while in a python venv.

I have no clue as to the internal cause of the error I described at the beginning. Any comments are welcomed

**Comment by albertosottile** [comment]
I think `py2exe` is capable of handling your requirements. The problem you are reporting is happening because of an unfinished `git stash apply` in your code, see here:
https://github.com/PinkDev1/Terraria-Colourfull-Chat/blob/ebb39d976fde417a2b8618499c695bb3882b051f/TerrariaRainbowChat.py#L6-L10

I would suggest you to fix the code and execute it independently (so, `python3 TerrariaRainbowChat.py`, to verify that it works) before attempting again to pack it with `py2exe`.

**Comment by PinkDev1** [comment]
[Oh, you're right. Oops xd](https://i.kym-cdn.com/photos/images/newsfeed/001/262/452/8c1.png)
