### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'libname'

### ISSUE THREAD

**Issue by GA9BR** [py2exe/py2exe#55]
I'm new to programming and can't compile the exe, I get this error. I don't know how to fix it.
![Screenshot_80](https://user-images.githubusercontent.com/59209013/99615985-2d642500-29fb-11eb-8cec-634f1f1f047a.png)

**Comment by albertosottile** [comment]
Hi, please do not use the `build_exe` command but, instead, try to write your `setup.py` script. A few examples can be found in the repository (test folder, documentation strings) and in the close issues

**Comment by albertosottile** [comment]
Closing this as no further information was provided. Once again, I would advise you to write a `setup.py` script and try again. Feel free to open a new issue if you encounter other problems.
