### ISSUE TITLE
502 Bad Gateway for py2exe.org

### ISSUE THREAD

**Issue by mikeholler** [py2exe/py2exe#61]
I'm not sure the best place to put this, but the documentation points to links on http://py2exe.org, which are no longer working due to bad gateway.

**Comment by albertosottile** [comment]
Thanks for reporting this. While I do not maintain that server, I think that notifying its issues here is still helpful.

I checked now and the website seems to work well, hence I am closing this issue. Please feel free to reopen it if you still experience this error.
