### ISSUE TITLE
AssertionError: Distuitls has already been patched.

### ISSUE THREAD

**Issue by Chubek** [py2exe/py2exe#66]
Here's the error I'm getting after I run `python setup.py py2exe`:

```
AssertionError: distutils has already been patched by <class 'py2exe.patch_distutils.patch_distutils.<locals>.Distribution'>
```

My setup.py:

```
from distutils.core import setup
import py2exe

setup(console=['main.py'])
```

What's wrong?

**Comment by albertosottile** [comment]
Hello. Sometimes I have also seen this error, usually it happens when some of your imported packages tries to patch `distutils` again after `py2exe` has done the same. 

Could you provide me a minimal version of your `main.py` script that is sufficient to reproduce this issue? Thanks.

**Comment by Chubek** [comment]
> 
> 
> Hello. Sometimes I have also seen this error, usually it happens when some of your imported packages tries to patch `distutils` again after `py2exe` has done the same.
> 
> Could you provide me a minimal version of your `main.py` script that is sufficient to reproduce this issue? Thanks.

https://github.com/Chubek/steve-automation/blob/master/main.py

**Comment by albertosottile** [comment]
Thanks, but I would prefer a single, self-contained test script that I can use to directly reproduce the problem. The script you linked is importing a custom module (`gui`) which is quite extensive and not really minimal.

Two notes: 
- I just released version [0.10.2.0](https://github.com/py2exe/py2exe/releases/tag/v0.10.2.0), which included several fixes in this area. I would encourage you to try again with this version.
- As you can see from [here](https://ci.appveyor.com/project/albertosottile/py2exe-iupeb/builds/37410675), the CI already includes a `tkinter` [test](https://github.com/py2exe/py2exe/blob/master/tests/functional/tk_test/tk_test.py) that is currently passing with the latest builds.

**Comment by albertosottile** [comment]
Closing this as no further input was provided. Please feel free to reopen anytime if you can provide a self-contained test script.

**Comment by dee42** [comment]
If anyone else comes across this instance, you just need to make sure setuptools is imported before py2exe to prevent it.
