### ISSUE TITLE
Python 3.9 fails with AttributeError: 'Namespace' object has no attribute 'libname'

### ISSUE THREAD

**Issue by jtmoon79** [py2exe/py2exe#68]
A simple program for `py2exe` fails with error `AttributeError: 'Namespace' object has no attribute 'libname'`.

## reproduction steps

Using Windows  10, PowerShell 7.1.1, and python.org CPython version 3.9.0.
`py2exe` version `0.10.2.0`.

### virtualenv setup

```
PS1> New-Item -Path "test1" -ItemType directory
PS1> Set-Location test1
PS1> python --version
Python 3.9.0
PS1> python -m virtualenv .venv3win
PS1> .\.venv3win\Scripts\activate.ps1
PS1> pip install py2exe
```

#### `myprogram.py`

```
#!/usr/bin/env python3

print("this is my program")
```

#### `setup.py`

```
from setuptools import setup
from setuptools import find_packages
import py2exe
setup(
    name="myprogram",
    version="0.1",
    install_requires=[],
    setup_requires=["wheel"],
    scripts=["myprogram.py"],
    entry_points={
        "console_scripts": [
            "myprogram.py=myprogram.py:main",
        ],
    },
    options={
        "py2exe": {
            "compressed": False,
            "unbuffered": True,
            "xref": True,
            "optimize": 2,
            "bundle_files": 1,
        },
    },
    console=["myprogram.py"],
)
```

### failure

```
PS1> python -m py2exe .\myprogram.py  -v
INFO:runtime:Analyzing the code
INFO:runtime:Found 472 modules, 4 are missing, 0 may be missing

  4 missing Modules
  ------------------
? _posixshmem                         imported from multiprocessing.resource_tracker, multiprocessing.shared_memory
? _testinternalcapi                   imported from test.support
? readline                            imported from cmd, code, pdb
? resource                            imported from test.support
Traceback (most recent call last):
  File "C:\Python\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Project\test1\.venv3win\lib\site-packages\py2exe\__main__.py", line 8, in <module>
    build_exe.main()
  File "C:\Project\test1\.venv3win\lib\site-packages\py2exe\build_exe.py", line 138, in main
    builder.build()
  File "C:\Project\test1\.venv3win\lib\site-packages\py2exe\runtime.py", line 238, in build
    self.build_exe(target, exe_path, options.libname)
AttributeError: 'Namespace' object has no attribute 'libname'
```

**Comment by albertosottile** [comment]
Hello, 

`py2exe` is effectively a `distutils` extension (though now is more a `setuptools` extenstion...). Hence, you should run it via

```
python setup.py py2exe
```

and not as an independent module. Options such as `verbose` can be passed in the `py2exe` dictionary in the setup script. I tried running your test code in this way and confirmed that it works as expected.

Furthermore, unfortunately bundling from a virtual environment is not supported in general. This constrain comes from the further complications introduced by this layer in the already vast and diverse ecosystem of all Python packages, combined with my limited time. Should you encounter issues with `venv`, I will encourage you to refrain from using it to get support (note that in this issue the virtual environment was indeed irrelevant).

If you want to have the isolation and environment stability provided by a virtual environment, my advice would be to use Docker Windows containers.

**Comment by albertosottile** [comment]
I inteprtet the 👍 as a sign that you managed to use `py2exe`, hence I am closing this now. Feel free to reopen it or open a new issue if you still experience this or a different problem.

**Comment by strathfield-council** [comment]
I tried to use the above setup.py and python setup.py py2exe. I got the following error
? pymssql.Error  import from __script__
