### ISSUE TITLE
Created executable with py2exe does not work with PEP 420 namespace

### ISSUE THREAD

**Issue by Mikayex** [py2exe/py2exe#70]
Support for PEP 420 (implicit namespaces) was a great news for 0.10.2.0 ! However it is not yet functional...
Yes the package is correctly found and added to library.zip at compile time, but at runtime it cannot be imported.

You can find a minimum exemple [here](https://github.com/Mikayex/py2exe_pep420).

In this exemple, running the exe gives me:
```
Traceback (most recent call last):
  File "app.py", line 1, in <module>
ModuleNotFoundError: No module named 'my_namespace'
```

As a workaround I can put a `__init__.py` file in my namespace with:
```py
__path__ = __import__('pkgutil').extend_path(__path__, __name__)
```
but this is pretty annoying...

Python version: 3.9.0
py2exe version: 0.10.2.1

**Comment by albertosottile** [comment]
Thanks for having reported this. I have a test in place for PEP420 based on `zope.interface` but, apparently, `ModuleSpec.origin` can either be `None` or `'namespace'` in this kind of packages, and I was only detecting the latter. Further information here: https://docs.python.org/3/library/importlib.html#importlib.machinery.ModuleSpec.origin

I just pushed a fix in the `develop` branch. Could you download the relevant wheels for you from the latest GitHub Action artifacts here:
https://github.com/py2exe/py2exe/actions/runs/600268062

unzip them, install them. and double check if this fixes the error also for you? Thank you for your assistance.

**Comment by Mikayex** [comment]
Thanks for the quick response !
Yes that fixes the problem.
