### ISSUE TITLE
Detecting running under py2exe

### ISSUE THREAD

**Issue by selfisekai** [py2exe/py2exe#74]
How can I detect/check whether my Python app is running from a build generated by py2exe, or from source code/wheel?

**Comment by urishab** [comment]
```
import sys
py2exe_mode = hasattr(sys,'frozen')
```

**Comment by albertosottile** [comment]
Thanks @urishab for the quick reply you gave here! @selfisekai , I am closing this for now, feel free to open a new issue if you have any further question.
