### ISSUE TITLE
ValueError: py.__spec__ is not set with pandas library

### ISSUE THREAD

**Issue by raj5287** [py2exe/py2exe#79]
Hi, I am getting this error with pandas library.
error: `ValueError: py.__spec__ is not set`
 setup.py is :
```
from distutils.core import setup
import py2exe

setup(console=['test.py'], options={"py2exe": {"packages": ['pandas']}})
```
test.py is :
```
import pandas as pd
df = pd.DataFrame([1,2], columns=['a'])
```
pandas version = (1.1.2)
py2exe version = (0.10.3.0)
python version = 3.7.6

**Comment by albertosottile** [comment]
Hi, 

you are experiencing an upstream bug, see https://bugs.python.org/issue35791, https://github.com/pytest-dev/apipkg/issues/13 and https://bugs.python.org/issue35839. Hence, I do not think that I will fix this (I am not even sure how, perhaps I could just exclude the `py` package from importing, but then something else could break down the road...)

Personally, I would suggest a workaround to avoid this bug: do not use the `"packages"` option in your setup script to embed the full `pandas` package in your executable.Iinstead, let `ModuleFinder` to its job. This will result in a slimmer executable and it will also avoid the need to install `pytest` (which I had to do to reproduce your error). As you can see from the [Actions job](https://github.com/py2exe/py2exe/actions/runs/649258469), the [`pandas` test](https://github.com/py2exe/py2exe/tree/master/tests/functional/pandas_test) runs well and it does not use this option.

Depending on how complex is your actual code, this might or might not work out of the box. It could be that you need to include specific modules with the `includes` keyword.  

Please let me know if removing this option fixes building the example code also for you. If you then experience other problems with your actual code, I would encourage you to open new issues about them. Thanks.

**Comment by raj5287** [comment]
Hi,
I used this 'options={"py2exe": {"packages": ['pandas']}}' because I was getting the above mentioned error. Anyway, I tried again and am getting the same error. Could you please explain a bit about how to resolve this on my end?

**Comment by raj5287** [comment]
Hi,
I used this 'options={"py2exe": {"packages": ['pandas']}}' because I was getting the above mentioned error. Anyway, I tried again and am getting the same error. Could you please explain a bit about how to resolve this on my end?

**Comment by albertosottile** [comment]
I am not really sure how to help you, as I cannot reproduce and the CI is running a similar test well. Could you take the `pandas` test code from [here](https://github.com/py2exe/py2exe/tree/master/tests/functional/pandas_test), run it locally, and see if that works on your system? Thanks.

**Comment by raj5287** [comment]
Hi
Thanks for all the help. I guess there is some issue with the environment, cause I tried in a new conda environment with just python and pandas installed, everything working fine. Sorry for all the troubles
