### ISSUE TITLE
Copy hook for Crypto package to cover Cryptodome package

### ISSUE THREAD

**Issue by khuston** [py2exe/py2exe#82]
Pycryptodome can be installed under two package names - [Crypto](https://pypi.org/project/pycryptodome/) or [Cryptodome](https://pypi.org/project/pycryptodomex/). Weird, but I guess [pycrypto](https://pypi.org/project/pycrypto/) already used the Crypto package name, so Pycryptodome offers to use the same package name (Crypto) to serve as a drop-in replacement, or it can use a different package name (Cryptodome) to run alongside Pycrypto using the Crypto package name.

Anyway, I'm thankful to see that a py2exe hook for the Crypto package was recently added. All it takes to support the Cryptodome package name is a copy-and-paste, find-and-replace (Crypto->Cryptodome). I could create a pull request for this.

**Comment by albertosottile** [comment]
I realized this duality while I implemented the hook for `Crypto`, but I did not implement one also for `Cryptodome` as I thought there was no demand. I would welcome a pull request along the lines you suggest above, perhaps with an eye towards reusing as much code as possible from the already existing hook function.

**Comment by albertosottile** [comment]
Closed by #83.
