### ISSUE TITLE
Question:  py -3.4 -m py2exe.build_exe myscript.py

### ISSUE THREAD

**Issue by zxo102** [py2exe/py2exe#89]
Hi there, 
      I am using anaconda 3 (python 3.8) of windows10.  
     As indicated in the title,  anybody knows how to run the command: 
           py -3.4 -m py2exe.build_exe myscript.py    
    
   Thanks a lot.

**Comment by albertosottile** [comment]
The command you are using is outdated. I would encourage you to make a `setup.py` script as described in http://www.py2exe.org/index.cgi/Tutorial.
