### ISSUE TITLE
soundfile: cannot load library with bundle_files = 0

### ISSUE THREAD

**Issue by dallouper** [py2exe/py2exe#91]
Numpy now works fine with the dll embedded in the exe which is great.

But with other dlls, like soundfile, the exe fails with either a silent crash or errors like the one in the title. Using a hook to insert it into the bundle does not, alone, solve the issue. In this case it tries to load it via cffi with a path as parameter.

**Comment by albertosottile** [comment]
Hello, could you provide a minimal example of this failure? Ideally, a python script that uses the library you want to embed and runs a minimal test of it, plus the corresponding `setup.py` script. Thanks.

**Comment by dallouper** [comment]
Hi, sure, it fails right at ‘import soundfile’ with the error:

Traceback (most recent call last):
  File "soundfile.pyc", line 142, in <module>
OSError: sndfile library not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "module1.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "zipextimporter.pyc", line 88, in load_module
  File "soundfile.pyc", line 163, in <module>
OSError: cannot load library 'C:\dist\_soundfile_data\libsndfile64bit.dll': error 0x7e

Setup.py:

from distutils.core import setup
import py2exe, sys
sys.argv.append('py2exe')
setup(name='App',
    options = {'py2exe': {'bundle_files': 0,
                 'compressed': True,
                 }},
    windows = [{
        'script': 'module1.py',
        }],
    zipfile = None,
)

But using only the code above, the file libsndfile64bit.dll is not packed in to the exe maybe because soundfile loads it via cffi, of which it is dependent. Setting up a hook gets the dll into the exe but it still doesn't work. I mentioned numpy because these tests yield the same result with other dlls (like cryptography or cv2) and used to with numpy. So I thought that what you did with numpy might be replicated with other dlls.

**Comment by albertosottile** [comment]
Most likely, the `libsndfile64bit.dll` library depends on other DLLs that have to be copied in the bundle. If that is the case, however, I am surprised that the hook does not get also those. Could you report here the error message you get if you set up a hook to copy the sndfile DLL?

**Comment by dallouper** [comment]
Perhaps I should qualify what I meant by “set up a hook”. By reading the project issues I figured that the way to include a dll had something to do with a feature called “hook” and also that it happened to exist a file named hooks.py in the py2exe folder that might have something to do with it. So I copied the function hook__ssl there and adapted it like this:

def hook_soundfile(finder, module):
    finder.add_dll(os.path.dirname(sys.executable)+'/Lib/site-packages/_soundfile_data/libsndfile64bit.dll')

which works insofar that the resulting exe has the dll bundled in, but the program fails with:

Traceback (most recent call last):
  File "soundfile.pyc", line 142, in <module>
OSError: sndfile library not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "module1.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "zipextimporter.pyc", line 88, in load_module
  File "soundfile.pyc", line 163, in <module>
OSError: cannot load library 'C:\dist\_soundfile_data\libsndfile64bit.dll': error 0x7e

**Comment by dallouper** [comment]
Sorry, couldn't find a way to fix the typos in the previous post. Here it is corrected:

Should qualify what I meant by “set up a hook”. By reading the project issues I figured that the way to include a dll had something to do with a feature called “hook” and also that it happened to exist a file named hooks.py in the py2exe folder that might have something to do with it. So I copied the function hook__ssl and adapted it like this:

def hook_soundfile(finder, module):
   finder.add_dll(os.path.dirname(sys.executable)+'/Lib/site-packages/_soundfile_data/libsndfile64bit.dll')

which works insofar that the resulting exe has the dll bundled in, but the program fails with:

Traceback (most recent call last):
  File "soundfile.pyc", line 142, in <module>
OSError: sndfile library not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "module1.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "zipextimporter.pyc", line 88, in load_module
  File "soundfile.pyc", line 163, in <module>
OSError: cannot load library 'C:\dist\\_soundfile_data\libsndfile64bit.dll': error 0x7e

**Comment by dallouper** [comment]
Just to add that the section in soundfile.pyc where the exe fails has the following code (line 163 is the last):

    try:
        _libname = _find_library('sndfile')
        if _libname is None:
            raise OSError('sndfile library not found')
        _snd = _ffi.dlopen(_libname)
    except OSError:
        if _sys.platform == 'darwin':
            _libname = 'libsndfile.dylib'
        elif _sys.platform == 'win32':
            from platform import architecture as _architecture
            _libname = 'libsndfile' + _architecture()[0] + '.dll'
        else:
            raise

        # hack for packaging tools like cx_Freeze, which
        # compress all scripts into a zip file
        # which causes __file__ to be inside this zip file

        _path = _os.path.dirname(_os.path.abspath(__file__))

        while not _os.path.isdir(_path):
            _path = _os.path.abspath(_os.path.join(_path, '..'))

        _snd = _ffi.dlopen(_os.path.join(
            _path, '_soundfile_data', _libname))

**Comment by dallouper** [comment]
Also, if in hooks.py add_datafile_to_zip is used instead of add_dll so that, inside the bundle, the dll is in a folder named _soundfile_data, it makes no difference.

**Comment by albertosottile** [comment]
Sorry, I did not have the time to reply to you sooner. 

> `OSError: cannot load library 'C:\dist\_soundfile_data\libsndfile64bit.dll': error 0x7e`

This essentially means the library was correctly found but it was not loaded because one **dependency** could not be found.  

I would advice to use a tool, e.g. [Dependency Walker](http://www.dependencywalker.com/), on `libsndfile64bit.dll` to see which is the missing library and copy also that in the executable folder. If this solves the problem, then you can add the missing DLL in the hook code.

> Also, if in hooks.py add_datafile_to_zip is used instead of add_dll so that, inside the bundle, the dll is in a folder named _soundfile_data, it makes no difference.

To add the DLL, I would use `add_dll`, as the Python bootloader alone is not able to import the DLL from the zipfile (that requires `_memimporter` and `bundle_files < 2`, but that opens a whole new set of potential problems).

**Comment by dallouper** [comment]
Loading the dll from the exe file (‘bundle_files’: 0) is the whole point.

I embedded all dependencies anyway (kernel32.dll, user32.dll and msvcrt.dll) and it made no difference.

All dlls mentioned (cryptography, cv2, soundfile) work fine if they are in the dist directory. The ‘potential problems’ you mention are, I reckon, the actual problems.

That is why I mentioned numpy. Its dll used to only work outside the exe file but now it works from within it. I’m trying to replicate that.

**Comment by albertosottile** [comment]
Sorry, I must have missed when you said you were using `bundle_files = 0`. In that case, I am afraid I cannot help you. There are at least a dozen reasons why loading a library via `_memimporter` could fail, as that is not the fefault method of loading libraries on Windows. 

If you are interested in debugging this, I would suggest you to build py2exe with debug symbols and perhaps to obtain a debug version of the library you are trying to load, then use a debugger (e.g. WinDbg) to find out why your app is not working. 

As I mentioned before, I do not have the capacity to support `bundle_files < 3` for packages outside the standard library. I willleave this issue open for a while in case someone else can help you in this endeavor.

**Comment by dallouper** [comment]
How do you direct it to be loaded by `_memimporter`?

At the moment it seems that is being loaded by `cffi` as `soundfile` tells it to and then, because it can't find the dll on the executable folder, it fails.

I recall `numpy` dll had the same problem as simply embeding the file wouldn't work. How was it solved?

**Comment by albertosottile** [comment]
Closing this as active support for `bundle_files < 2` is limited to the Python standard library. Regarding your question about `numpy`, I would be surprised if `numpy` currently works with `bundle_files = 0`. 

If you still want to debug this, I would encourage to proceed as described in the previous comment:
> If you are interested in debugging this, I would suggest you to build py2exe with debug symbols and perhaps to obtain a debug version of the library you are trying to load, then use a debugger (e.g. WinDbg) to find out why your app is not working.
