### ISSUE TITLE
error: [WinError 87] The parameter is incorrect.

### ISSUE THREAD

**Issue by Tacorico787** [py2exe/py2exe#95]
I tried running py2exe on a python project I'm doing, and I got the error shown above. Haven't been able to find any fixes anywhere. Here is my setup file:

`from distutils.core import setup 
import py2exe

setup(console=['GUI.py'])`

And this is the full message I get:
`running py2exe
selenium\webdriver\firefox\firefox_profile.pyc:208: SyntaxWarning: "is" with a literal. Did you mean "=="?

  12 missing Modules
  ------------------
? PIL                                 imported from openpyxl.drawing.image
? Queue                               imported from urllib3.util.queue
? _posixshmem                         imported from multiprocessing.resource_tracker, multiprocessing.shared_memory
? backports                           imported from urllib3.packages.ssl_match_hostname
? brotli                              imported from urllib3.response, urllib3.util.request
? collections.Mapping                 imported from urllib3._collections
? collections.MutableMapping          imported from urllib3._collections
? defusedxml                          imported from openpyxl.xml, openpyxl.xml.functions
? numpy                               imported from openpyxl.compat.numbers
? openpyxl.tests                      imported from openpyxl.reader.excel
? readline                            imported from cmd, code, pdb
? test                                imported from multiprocessing.util
Building 'dist\GUI.exe'.
error: [WinError 87] The parameter is incorrect.`

Any help would be appreciated. I'm running Python 3.9

**Comment by albertosottile** [comment]
Hello, without knowing the content of your application file (`GUI.py`) is quite hard to help you. What you could try to do is to build with a more verbose log by changing your `setup.py` script as in

```python
from distutils.core import setup
import py2exe

setup(console=[{"script": "GUI.py"}],
      options={"py2exe": {
               "verbose": 4}
              },
     )
```

and report here the longer log output.

**Comment by albertosottile** [comment]
According to #97, this issue should be solved by uninstalling the Python version provided by the Microsoft Store, and installing it again from the official Python website.
