### ISSUE TITLE
error: [WinError 87] The parameter is incorrect

### ISSUE THREAD

**Issue by fuckcuff** [py2exe/py2exe#97]
i was using the latest version of py2exe and i was getting this same problem
i have now switched to an older version because someone who is compiling this same program as me is using it and it works for them. i am now using 0.10.2 but i am still getting the same error
i am now using python 3.7 but i couldnt compile this program with python 3.9 either.
here is a screenshot of the error and the code of the file which is being compiled.
![image](https://user-images.githubusercontent.com/67871539/128792768-6efe3484-3df4-41af-9547-55cc5b748e2b.png)

there is no issue with the ShadowSharkPayload.py file because i can run it with `python ShadowSharkPayload.py` and it works without any problems

**Comment by albertosottile** [comment]
Hello, 

I would give you the same advice I gave in #95: please build again with a higher value of the `verbose` flag in `setup.py` and report here the extended console output.

**Comment by fuckcuff** [comment]
heres what happened when i did that:
```
running py2exe

  1 missing Modules
  ------------------
? readline                            imported from cmd, code, pdb
Building 'dist\ShadowSharkPayload.exe'.
Add resource PYTHONSCRIPT/1(3392 bytes) to dist\ShadowSharkPayload.exe
error: [WinError 87] The parameter is incorrect.
```
![image](https://user-images.githubusercontent.com/67871539/129818317-fb93246d-4d8b-4559-a4fa-b88f233c6598.png)

**Comment by fuckcuff** [comment]
hello

**Comment by EnderC00kiez** [comment]
If you are still having this issue, try
`pip install pyreadline`
or
`pip3 install pyreadline`

**Comment by fuckcuff** [comment]
> If you are still having this issue, try
> `pip install pyreadline`
> or
> `pip3 install pyreadline`

thanks for the help, now im getting the same error but with different missing modules

![image](https://user-images.githubusercontent.com/67871539/132242254-b39d9e29-bb13-49da-925d-a7c4c7b6f264.png)

**Comment by fuckcuff** [comment]
FIXED BY UNINSTALLING PYTHON AND INSTALLING IT FROM THE OFFICIAL WEBSITE (i had it installed from microsoft store)

**Comment by albertosottile** [comment]
Good to know that you solved this :) I will now close this issue and recommend this solution to other people that are experiencing it.
